name: Flask App CI/CD Pipeline

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pytest

      - name: Deploy to Staging
        if: github.ref == 'refs/heads/staging'
        run: |
          # Add your deployment steps for staging here
          echo "Deploying to Staging"

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: |
          # Add your deployment steps for production here
          echo "Deploying to Production"
